### ISSUE TITLE
Test sequence labels

### ISSUE THREAD

**Issue by Maghoumi** [SFINGE3D/DatasetV1#1]
Hi @giach68,

Hope you are well! I enjoyed reading the SFINGE3D paper and glad to see this dataset.  
It seems that the test sequences (txt files in the `Sequences` directory) do not have labels. Do you plan on releasing the labeled version too?

Both myself and a colleague are interested in running some experiments on this dataset.

Thanks!

**Comment by giach68** [comment]
Dear Mehran,

sorry for the inconvenience.

I will check the repository and add the missing annotations

best regards

Andrea

**Comment by Maghoumi** [comment]
Andrea, no worries, thanks a lot!

**Comment by Maghoumi** [comment]
Hi Andrea,

Thanks for committing the ground truth labels to the repo. I think the formatting of the CSV file makes sense to me, but just double checking: is each line formatted as the following?

```
Seq number, gesture count in seq , gesture class,start,end,   gesture class, start, end .........
```

Thanks again for your prompt response and action.

**Comment by Maghoumi** [comment]
Thanks for the README. Closing this issue
